### ISSUE TITLE
:trollface: 

### ISSUE THREAD

**Issue by snerble** [avie0108/SEM#1]

**Comment by avie0108** [comment]
:trollface:

**Comment by snerble** [comment]
:trollface:
![VRChat_1920x1080_2022-06-17_02-34-58 538](https://user-images.githubusercontent.com/45596162/174637025-3c2333e5-c397-415d-bfc3-37e615562561.png)

**Comment by snerble** [comment]
awdawdawd
![VRChat_1920x1080_2022-06-17_02-22-54 435](https://user-images.githubusercontent.com/45596162/174637188-bd8fc9a1-4cf2-4d02-ac53-4320dbe239f0.png)

**Comment by snerble** [comment]
skill issue

**Comment by Grzegorz2121** [comment]
:trollface:

**Comment by Basroos** [comment]
![Fumo](https://user-images.githubusercontent.com/47592774/174639189-5445bcce-342f-4bb7-ba5c-44d8ccb82120.jpg)

**Comment by snerble** [comment]
![image](https://media.discordapp.net/attachments/726213612724813829/966897601607794698/taketh.gif)

**Comment by Grzegorz2121** [comment]
[Doom (game).zip](https://github.com/avie0108/SEM/files/8942037/Doom.game.zip)

**Comment by snerble** [comment]
![IMG_2105](https://user-images.githubusercontent.com/45596162/174639825-e56cb99d-e880-4504-afb9-969a2edce803.PNG)

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174639841-5974503f-7d3c-4578-be09-d68e389e4c5e.mov

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174639861-43ecd907-7839-486c-a416-cca777c51df5.mp4

**Comment by snerble** [comment]
![IMG_3255](https://user-images.githubusercontent.com/45596162/174639876-22af8a1f-792c-45ac-bc8e-c567eef79ea3.gif)

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174639897-f5daca06-8bcc-49a0-9360-ad3a6be0a065.mp4

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174639917-1510b0fd-dd3b-4890-ac90-d1987fa079ad.mp4

**Comment by Grzegorz2121** [comment]
GitHub Ban Speedrun any %

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174640034-700bfd20-fa10-4b86-9692-045f0071d40b.mov

**Comment by snerble** [comment]
https://user-images.githubusercontent.com/45596162/174640121-76eefeb7-9fdb-46fa-b078-1080daee8d1b.mp4


https://user-images.githubusercontent.com/45596162/174640123-e1ea0174-be10-4fba-aa99-39bf0293c7e4.mp4


https://user-images.githubusercontent.com/45596162/174640124-23c88235-8b4d-43f6-b2be-4d29805930d8.mp4

**Comment by snerble** [comment]
![TROLL](https://user-images.githubusercontent.com/45596162/174640169-4d1404bd-f57b-4f5c-a370-ef61e70c6b6c.gif)
