### ISSUE TITLE
Greg was here

### ISSUE THREAD

**Issue by Grzegorz2121** [avie0108/SEM#3]
unyu?

**Comment by avie0108** [comment]
unyu

**Comment by Basroos** [comment]
![getoUT](https://user-images.githubusercontent.com/47592774/174638941-fd932ff4-4a1c-451b-938c-fafbcc2080fb.jpg)

**Comment by gidion** [comment]
![boompske](https://user-images.githubusercontent.com/13356287/174638975-62ec6b45-5b56-423d-bcf3-525352e93f9f.png)

**Comment by gidion** [comment]
![bossie](https://user-images.githubusercontent.com/13356287/174638992-29436493-6f82-4465-9d2a-c4ef7ddc09bc.png)

**Comment by Basroos** [comment]
![clipart2771263](https://user-images.githubusercontent.com/47592774/174639082-26c15b4d-688b-4c18-98b2-9c10de5d5c24.png)
